before_script:
  - "npm install"
  - "grunt"

stages:
  - test

check_v0_10:
  script:
    - "cd tests && ./test_all.sh"
    - "node pearsonbplustree.js 1000000"
  stage: test
  tags:
    - v0_10

check_v5:
  script:
    - "cd tests && ./test_all.sh"
    - "node pearsonbplustree.js 1000000"
  stage: test
  tags:
    - v5
