before_script:
  - "npm install"
  - "grunt"

stages:
  - test

check_v0_10:
  script: "cd tests && ./test_all.sh"
  stage: test
  tags:
    - v0_10

check_v5:
  script: "cd tests && ./test_all.sh"
  stage: test
  tags:
    - v5
